# Generated by Django 4.2.3 on 2023-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_descuentos_populares_todos_rename_estudiante_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='email',
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
