# Generated by Django 4.2.3 on 2023-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_carrito_apellido_remove_carrito_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='todos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
